---
abstract: 'Launchpad.net OAuth 1.0'
author:
  - 'Adam Stokes, C<< <adamjs at cpan.org> >>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  bareword::filehandles: 0
  indirect: 0
  multidimensional: 0
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OAuth-LP
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Class::Load: 0
  IO::Socket::SSL: 0
  Mojolicious: 0
  Net::OAuth: 0
  URI: 0
  URI::Encode: 0
  URI::QueryParam: 0
resources:
  bugtracker: https://github.com/battlemidget/Net-OAuth-LP/issues
  homepage: https://github.com/battlemidget/Net-OAuth-LP
  repository: https://github.com/battlemidget/Net-OAuth-LP.git
version: 0.020
x_contributors:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
  - 'Adam Stokes <hackr@cypherbook.com>'
