---
abstract: 'Launchpad.net OAuth 1.0'
author:
  - "Adam 'battlemidget' Stokes, C<< <adamjs at cpan.org> >>"
build_requires:
  Test::More: 0
  bareword::filehandles: 0
  indirect: 0
  multidimensional: 0
configure_requires:
  Module::Build::Tiny: 0.026
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OAuth-LP
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  HTTP::Request: 0
  HTTP::Request::Common: 0
  Hash::AsObject: 0
  IO::Socket::SSL: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  List::Objects::WithUtils: 0
  Method::Signatures: 0
  Moo: 0
  Moo::Role: 0
  Net::OAuth: 0
  Types::Standard: 0
  URI: 0
  URI::Encode: 0
  URI::QueryParam: 0
  perl: v5.10.0
  strictures: 1
resources:
  bugtracker: https://github.com/battlemidget/Net-OAuth-LP/issues
  homepage: https://github.com/battlemidget/Net-OAuth-LP
  repository: https://github.com/battlemidget/Net-OAuth-LP.git
version: 0.016
x_contributors:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
  - 'Adam Stokes <hackr@cypherbook.com>'
