---
abstract: 'Authorization/Authentication against Launchpad.net'
author:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OAuth-LP
requires:
  HTTP::Request: 0
  HTTP::Request::Common: 0
  Hash::AsObject: 0
  JSON: 0
  LWP::UserAgent: 0
  List::Objects::WithUtils: 0
  Method::Signatures: 0
  Moo: 0
  Moo::Role: 0
  Net::OAuth: 0
  Types::Standard: 0
  URI: 0
  URI::Encode: 0
  URI::QueryParam: 0
  perl: v5.10.0
  strictures: 1
resources:
  homepage: https://github.com/battlemidget/Net-OAuth-LP
  repository: https://github.com/battlemidget/Net-OAuth-LP.git
version: 0.015_01
