---
abstract: 'Authorization/Authentication against Launchpad.net'
author:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
build_requires:
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OAuth-LP
requires:
  Browser::Open: 0
  File::Spec::Functions: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  List::Compare: 0
  Moose: 0
  MooseX::Method::Signatures: 0
  MooseX::StrictConstructor: 0
  Net::OAuth: 0
  URI: 0
  URI::Encode: 0
  URI::QueryParam: 0
  Util::Any: 0
  namespace::autoclean: 0
resources:
  homepage: https://github.com/battlemidget/Net-OAuth-LP
  repository: https://github.com/battlemidget/Net-OAuth-LP.git
version: 0.001
